Repository TencentBlueKing/bk-bcs, pull requests merged in 2019-10, with the labels that each got.

#218 1.14.x
  Makefile
  install/cmd/conf/bcs-api/bcs-api.json.template
  install/cmd/conf/bcs-check/bcs-check.json.template
  install/cmd/conf/bcs-dns/bcs-dns.json.template
  install/cmd/conf/bcs-exporter/bcs-exporter.json.template
  install/cmd/conf/bcs-health-master/bcs-health-master.json.template
  install/cmd/conf/bcs-health-slave/bcs-health-slave.json.template
  install/cmd/conf/bcs-hpacontroller/bcs-hpacontroller.json.template
  install/cmd/conf/bcs-mesos-driver/bcs-mesos-driver.json.template
  install/cmd/conf/bcs-mesos-watch/bcs-mesos-watch.json.template
  install/cmd/conf/bcs-metricservice/bcs-metricservice.json.template
  install/cmd/conf/bcs-netservice/bcs-netservice.json.template
  install/cmd/conf/bcs-scheduler/bcs-scheduler.json.template
  install/cmd/conf/bcs-service-prometheus/bcs-service-prometheus.json.template
  install/cmd/conf/bcs-storage/bcs-storage.json.template
  install/cmd/conf/bmsf-mesos-adapter/bmsf-mesos-adaptor.json.template
Labels: confirmed, inner

#216 feature: add new metric error type in netservice; issue #213
  Gopkg.toml
  Makefile
  bcs-common/pkg/storage/zookeeper/nsclient.go
  bcs-services/bcs-dns/plugin/log/log.go
  bcs-services/bcs-dns/plugin/log/log_test.go
  bcs-services/bcs-dns/plugin/log/setup.go
  bcs-services/bcs-dns/plugin/log/setup_test.go
  bcs-services/bcs-netservice/netservice/allocatorService.go
  bcs-services/bcs-netservice/netservice/hostService.go
  bcs-services/bcs-netservice/netservice/ipinstance.go
  bcs-services/bcs-netservice/netservice/poolService.go
  bcs-services/bcs-netservice/netservice/service.go
  bcs-services/bcs-network/qcloud-eip/conf/conf.go
  bcs-services/bcs-network/qcloud-eip/eip/eip.go
  bcs-services/bcs-network/qcloud-eip/eip/instance.go
  bcs-services/bcs-network/qcloud-eip/eip/interface.go
  bcs-services/bcs-network/qcloud-eip/eip/netservice.go
  bcs-services/bcs-network/qcloud-eip/eip/network.go
  bcs-services/bcs-network/qcloud-eip/eip/network_test.go
  bcs-services/bcs-network/qcloud-eip/eip/routemap.go
  bcs-services/bcs-network/qcloud-eip/eip/routemap_test.go
  bcs-services/bcs-network/qcloud-eip/eip/util.go
  bcs-services/bcs-network/qcloud-eip/eip/vpc.go
  bcs-services/bcs-network/qcloud-eip/main.go
  bcs-services/bcs-network/qcloud-eip/option/option.go
  bcs-services/bcs-network/qcloud-eip/utils/command.go
Labels: confirmed, document, feature, inner, service

#225 feature: support whitelist auth in bcs-api, issue #224
  bcs-services/bcs-api/auth/bkiam/auth.go
  bcs-services/bcs-api/options/options.go
Labels: confirmed, inner, service

#230 fix: fix mesos-adapter nodewatch init bug, issue #229
  bcs-common/pkg/storage/zookeeper/util.go
Labels: bug, confirmed, enhancement, inner, service

#228 fix: zkclient CreateNode fails with node already exists, issue #227
  bcs-common/common/zkclient/zkclient.go
Labels: bug, confirmed, inner, service

#235 fix: deployment update process error, issue #0
  bcs-mesos/bcs-scheduler/src/manager/sched/backend/deployment.go
Labels: confirmed, enhancement, feature, inner, service

#239 修复DNS与netservice日志缺失问题
  Makefile
  bcs-common/pkg/storage/zookeeper/util.go
  bcs-mesos/bcs-container-executor/app/option.go
  bcs-mesos/pkg/apis/apis.go
  bcs-mesos/pkg/controller/controller.go
  bcs-mesos/pkg/webhook/webhook.go
  bcs-services/bcs-dns/plugin.cfg
  bcs-services/bcs-dns/plugin/bcsscheduler/events.go
  bcs-services/bcs-dns/plugin/log/README.md
  bcs-services/bcs-dns/plugin/log/log.go
  bcs-services/bcs-dns/plugin/log/setup.go
  bcs-services/bcs-netservice/main.go
  bcs-services/bcs-netservice/netservice/poolService.go
  install/cmd/conf/bcs-api/bcs-api.json.template
  install/cmd/conf/bcs-api/start.sh.template
  install/cmd/conf/bcs-api/stop.sh.template
  install/cmd/conf/bcs-check/bcs-check.json.template
  install/cmd/conf/bcs-dns/bcs-dns.json.template
  install/cmd/conf/bcs-dns/start.sh.template
  install/cmd/conf/bcs-dns/stop.sh.template
  install/cmd/conf/bcs-exporter/bcs-exporter.json.template
  install/cmd/conf/bcs-health-master/bcs-health-master.json.template
  install/cmd/conf/bcs-health-slave/bcs-health-slave.json.template
  install/cmd/conf/bcs-hpacontroller/bcs-hpacontroller.json.template
  install/cmd/conf/bcs-mesos-driver/bcs-mesos-driver.json.template
  install/cmd/conf/bcs-mesos-watch/bcs-mesos-watch.json.template
  install/cmd/conf/bcs-metricservice/bcs-metricservice.json.template
  install/cmd/conf/bcs-netservice/bcs-netservice.json.template
  install/cmd/conf/bcs-netservice/start.sh.template
  install/cmd/conf/bcs-netservice/stop.sh.template
  install/cmd/conf/bcs-scheduler/bcs-scheduler.json.template
  install/cmd/conf/bcs-service-prometheus/bcs-service-prometheus.json.template
  install/cmd/conf/bcs-storage/bcs-storage.json.template
  install/cmd/conf/bcs-storage/start.sh.template
  install/cmd/conf/bcs-storage/stop.sh.template
  install/cmd/conf/bmsf-mesos-adapter/bmsf-mesos-adaptor.json.template
Labels: bug, confirmed, inner, service
