Repository TencentBlueKing/bk-bcs, pull requests merged in 2019-06, with the labels that each got.

#51 代码扫描
  README.md
Labels: confirmed, inner

#52 fix: godeps recursive by Sirupsen, issue #0
  Makefile
Labels: bug, confirmed, enhancement, inner

#54 合并readme英文版
  README.md
  README_cn.md
  docs/logo/logo_en.png
Labels: confirmed, document, inner
