Repository TencentBlueKing/bk-bcs, pull requests merged in 2019-08, with the labels that each got.

#122 Update README.md
  README.md
Labels: document, outer

#124 docs: update SaaS info in readme, issue #67
  README.md
  bcs-common/common/blog/blog-README.md
Labels: confirmed, document, inner

#125 1.14.x代码常规同步
  CONTRIBUTING.md
  README.md
  bcs-common/common/blog/blog-README.md
  bcs-mesos/bcs-container-executor/executor/executor.go
  docs/features/k8s/image/bcs-api.png
  docs/features/k8s/基于k8s的容器编排.md
  install/cmd/conf/bcs-api/config_file.json.template
Labels: confirmed, inner

#127 修复首页链接错误
  README.md
Labels: confirmed, document, inner

#128 1.14.x常规合并
  README.md
Labels: document, inner

#132 feature: adjust config, issue #0
  install/community_edition/service/#etc#bcs#health-master.json
Labels: confirmed, document, inner

#133 feature: adjust config, issue #0
  install/community_edition/service/#etc#bcs#health-master.json
Labels: confirmed, document, inner

#135 feature: add tke cidr manager. issue #134
  bcs-services/bcs-api/pkg/models/cluster.go
  bcs-services/bcs-api/pkg/models/tke.go
  bcs-services/bcs-api/pkg/server/external-cluster/interface.go
  bcs-services/bcs-api/pkg/server/external-cluster/tke/tke.go
  bcs-services/bcs-api/pkg/server/resthdrs/cluster.go
  bcs-services/bcs-api/pkg/server/resthdrs/credentials.go
  bcs-services/bcs-api/pkg/server/resthdrs/handlers.go
  bcs-services/bcs-api/pkg/server/resthdrs/tke.go
  bcs-services/bcs-api/pkg/server/server.go
  bcs-services/bcs-api/pkg/storages/sqlstore/tke.go
Labels: confirmed, feature, inner

#142 feature: bcs-consoleproxy supports single session. issue #141
  bcs-mesos/bcs-consoleproxy/app/app.go
  bcs-mesos/bcs-consoleproxy/app/options/options.go
  bcs-mesos/bcs-consoleproxy/console-proxy/api/api.go
  bcs-mesos/bcs-consoleproxy/console-proxy/config/config.go
  bcs-mesos/bcs-consoleproxy/console-proxy/manager/console.go
  bcs-mesos/bcs-consoleproxy/console-proxy/manager/interface.go
  bcs-mesos/bcs-consoleproxy/console-proxy/manager/manager.go
  bcs-mesos/bcs-consoleproxy/console-proxy/types/types.go
  bcs-mesos/bcs-consoleproxy/console-proxy/util/util.go
Labels: confirmed, feature, inner

#146 mesos-datawatch支持prometheus采集特性
  bcs-mesos/bcs-mesos-watch/app/watch.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/app.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/configmap.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/deployment.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/endpoint.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/exportservice.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/mesos.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/metric.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/secret.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/service.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/taskgroup.go
  bcs-mesos/bcs-mesos-watch/servermetric/servermetric.go
  bcs-mesos/bcs-mesos-watch/storage/app.go
  bcs-mesos/bcs-mesos-watch/storage/cc.go
  bcs-mesos/bcs-mesos-watch/storage/configmap.go
  bcs-mesos/bcs-mesos-watch/storage/deployment.go
  bcs-mesos/bcs-mesos-watch/storage/endpoint.go
  bcs-mesos/bcs-mesos-watch/storage/exportservice.go
  bcs-mesos/bcs-mesos-watch/storage/metrics.go
  bcs-mesos/bcs-mesos-watch/storage/secret.go
  bcs-mesos/bcs-mesos-watch/storage/service.go
  bcs-mesos/bcs-mesos-watch/storage/taskgroup.go
  bcs-mesos/bcs-mesos-watch/types/types.go
  bcs-mesos/bcs-mesos-watch/util/util.go
  docs/features/prometheus/bcs-sulotion.md
Labels: confirmed, feature, inner

#143 prometheus对接bcs动态服务发现机制、bcs自身服务发现sdk
  Makefile
  bcs-common/pkg/discovery/node.go
  bcs-common/pkg/module-discovery/interface.go
  bcs-common/pkg/module-discovery/mesos-discovery.go
  bcs-common/pkg/module-discovery/services-discovery.go
  bcs-common/pkg/storage/zookeeper/util.go
  bcs-mesos/bcs-mesos-driver/mesosdriver/mesosdriver.go
  bcs-mesos/bcs-mesos-watch/app/watch.go
  bcs-services/bcs-sd-prometheus/app/app.go
  bcs-services/bcs-sd-prometheus/app/options/options.go
  bcs-services/bcs-sd-prometheus/config/config.go
  bcs-services/bcs-sd-prometheus/controller/controller.go
  bcs-services/bcs-sd-prometheus/discovery/bcs-mesos-discovery.go
  bcs-services/bcs-sd-prometheus/discovery/bcs-service-discovery.go
  bcs-services/bcs-sd-prometheus/discovery/interface.go
  bcs-services/bcs-sd-prometheus/discovery/node-discovery.go
  bcs-services/bcs-sd-prometheus/main.go
  bcs-services/bcs-sd-prometheus/types/types.go
Labels: confirmed, feature, inner

#148 1.14.1-alpha版本发布
  bcs-mesos/bcs-mesos-watch/storage/configmap.go
  docs/version/1.13.x.md
  docs/version/1.14.x.md
  docs/version/README.md
Labels: confirmed, document, inner

#150 docs: add template for netservice, issue #86
  docs/version/1.14.x.md
  install/cmd/conf/bcs-netservice/config_file.json.template
  install/cmd/conf/bcs-netservice/start.sh.template
  install/cmd/conf/bcs-netservice/stop.sh.template
Labels: confirmed, document, inner

#151 1.14.x
  docs/version/1.14.x.md
  install/cmd/conf/bcs-netservice/config_file.json.template
  install/cmd/conf/bcs-netservice/start.sh.template
  install/cmd/conf/bcs-netservice/stop.sh.template
Labels: confirmed, document, inner

#153 fix: fix a mistake. issue #152
  bcs-mesos/bcs-consoleproxy/console-proxy/manager/console.go
  bcs-services/bcs-api/main.go
Labels: bug, confirmed, inner

#154 docs: fix netservice template, issue #86
  install/cmd/conf/bcs-netservice/config_file.json.template
Labels: confirmed, document, inner

#158 迁移bcs-process-executor、bcs-process-daemon代码
  .gitignore
  Gopkg.lock
  Makefile
  bcs-mesos/bcs-process-daemon/main.go
  bcs-mesos/bcs-process-daemon/process-daemon/api/api.go
  bcs-mesos/bcs-process-daemon/process-daemon/config/config.go
  bcs-mesos/bcs-process-daemon/process-daemon/manager/download.go
  bcs-mesos/bcs-process-daemon/process-daemon/manager/interface.go
  bcs-mesos/bcs-process-daemon/process-daemon/manager/manager.go
  bcs-mesos/bcs-process-daemon/process-daemon/store/interface.go
  bcs-mesos/bcs-process-daemon/process-daemon/store/store.go
  bcs-mesos/bcs-process-executor/app/app.go
  bcs-mesos/bcs-process-executor/app/options/options.go
  bcs-mesos/bcs-process-executor/main.go
  bcs-mesos/bcs-process-executor/process-executor/driver/connection.go
  bcs-mesos/bcs-process-executor/process-executor/driver/driver.go
  bcs-mesos/bcs-process-executor/process-executor/driver/reader.go
  bcs-mesos/bcs-process-executor/process-executor/executor/executor.go
  bcs-mesos/bcs-process-executor/process-executor/executor/interface.go
  bcs-mesos/bcs-process-executor/process-executor/healthcheck/healthcheck.go
  bcs-mesos/bcs-process-executor/process-executor/proc-daemon/connection.go
  bcs-mesos/bcs-process-executor/process-executor/proc-daemon/daemon.go
  bcs-mesos/bcs-process-executor/process-executor/proc-daemon/interface.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/agent/agent.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/authentication/authentication.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/authorizer/authorizer.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/docker/spec.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/docker/v1/v1.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/docker/v2/v2.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/executor/executor.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/fetcher/fetcher.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/maintenance/maintenance.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/master/master.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/quota/quota.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/scheduler/scheduler.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/slave/containerizer.pb.go
  bcs-mesos/bcs-process-executor/process-executor/protobuf/slave/oversubscription.pb.go
  bcs-mesos/bcs-process-executor/process-executor/types/types.go
  scripts/vet.sh
  vendor/github.com/Microsoft/go-winio/archive/tar/common.go
  vendor/github.com/Microsoft/go-winio/archive/tar/reader.go
  vendor/github.com/Microsoft/go-winio/archive/tar/stat_atim.go
  vendor/github.com/Microsoft/go-winio/archive/tar/stat_atimespec.go
  vendor/github.com/Microsoft/go-winio/archive/tar/stat_unix.go
  vendor/github.com/Microsoft/go-winio/archive/tar/writer.go
Labels: confirmed, feature, inner, service

#160 bcs-storage支持prometheus metrics
  bcs-services/bcs-storage/storage/actions/lib/metrics.go
  bcs-services/bcs-storage/storage/actions/lib/process.go
  bcs-services/bcs-storage/storage/actions/lib/watch.go
  bcs-services/bcs-storage/storage/actions/lib/writer.go
  bcs-services/bcs-storage/storage/drivers/mongodb/metrics.go
  bcs-services/bcs-storage/storage/drivers/mongodb/scope.go
  bcs-services/bcs-storage/storage/drivers/mongodb/tank.go
  bcs-services/bcs-storage/storage/drivers/mongodb/watch.go
  bcs-services/bcs-storage/storage/drivers/zookeeper/metrics.go
  bcs-services/bcs-storage/storage/drivers/zookeeper/scope.go
  bcs-services/bcs-storage/storage/drivers/zookeeper/tank.go
  bcs-services/bcs-storage/storage/storage.go
  docs/features/prometheus/prometheus-intergration.drawio
  docs/features/prometheus/prometheus-intergration.png
Labels: confirmed, feature, inner, service

#163 add metrics and status api for bcs-loadbalance
  bcs-services/bcs-loadbalance/app/eventprocessor.go
  bcs-services/bcs-loadbalance/app/metric.go
  bcs-services/bcs-loadbalance/app/reflector.go
  bcs-services/bcs-loadbalance/image/config/haproxy.cfg
  bcs-services/bcs-loadbalance/image/config/haproxy.cfg.template
  bcs-services/bcs-loadbalance/image/start.sh
  bcs-services/bcs-loadbalance/main.go
  bcs-services/bcs-loadbalance/metrichelper/metricHelper.go
  bcs-services/bcs-loadbalance/monitor/monitor.go
  bcs-services/bcs-loadbalance/monitor/prometheus/prometheus.go
  bcs-services/bcs-loadbalance/monitor/status/status.go
  bcs-services/bcs-loadbalance/option/option.go
  bcs-services/bcs-loadbalance/rdiscover/rdiscover.go
  bcs-services/bcs-loadbalance/template/haproxy/haproxy.go
  bcs-services/bcs-loadbalance/template/haproxy/status.go
  bcs-services/bcs-loadbalance/template/manager.go
  bcs-services/bcs-loadbalance/template/nginx/nginx.go
  bcs-services/bcs-loadbalance/template/nginx/status.go
  docs/features/bcs-loadbalance/loadbalance.md
Labels: confirmed, feature, inner, service

#157 feature: add prometheus metrics for bcs-dns. issue #156
  bcs-mesos/bcs-consoleproxy/console-proxy/manager/console.go
  bcs-services/bcs-api/pkg/server/resthdrs/tke.go
  bcs-services/bcs-dns/plugin.cfg
  bcs-services/bcs-dns/plugin/bcscustom/handler.go
  bcs-services/bcs-dns/plugin/bcscustom/http.go
  bcs-services/bcs-dns/plugin/bcscustom/metrics.go
  bcs-services/bcs-dns/plugin/bcscustom/setup.go
  bcs-services/bcs-dns/plugin/bcsscheduler/controller.go
  bcs-services/bcs-dns/plugin/bcsscheduler/events.go
  bcs-services/bcs-dns/plugin/bcsscheduler/handler.go
  bcs-services/bcs-dns/plugin/bcsscheduler/metrics.go
  bcs-services/bcs-dns/plugin/bcsscheduler/scheduler.go
  bcs-services/bcs-dns/plugin/bcsscheduler/setup.go
  install/cmd/conf/bcs-api/config_file.json.template
  install/cmd/conf/bcs-dns/corefile.template
Labels: confirmed, feature, inner, service

#167 Dev mars
  bcs-services/bcs-loadbalance/app/eventprocessor.go
  bcs-services/bcs-loadbalance/option/option.go
Labels: confirmed, enhancement, inner, network

#165 feature: modify bcs-dns prometheus latency metric from millisecond to…
  bcs-services/bcs-api/main.go
  bcs-services/bcs-api/metric/metrics.go
  bcs-services/bcs-api/pkg/server/proxier/proxier.go
  bcs-services/bcs-api/pkg/server/resthdrs/bcs.go
  bcs-services/bcs-api/pkg/server/resthdrs/cluster.go
  bcs-services/bcs-api/pkg/server/resthdrs/credentials.go
  bcs-services/bcs-api/pkg/server/resthdrs/register_token.go
  bcs-services/bcs-api/pkg/server/resthdrs/tke.go
  bcs-services/bcs-api/pkg/server/resthdrs/user.go
  bcs-services/bcs-api/processor/http/actions/v4http/clusterkeeper/cluster-actions.go
  bcs-services/bcs-api/processor/http/actions/v4http/k8s/k8s-actions.go
  bcs-services/bcs-api/processor/http/actions/v4http/mesos/mesos-actions.go
  bcs-services/bcs-api/processor/http/actions/v4http/mesos/webconsole/webconsole.go
  bcs-services/bcs-api/processor/http/actions/v4http/mesos/webconsole/websocket-proxy.go
  bcs-services/bcs-api/processor/http/actions/v4http/metrics/metrics-actions.go
  bcs-services/bcs-api/processor/http/actions/v4http/netservice/netservice-actions.go
  bcs-services/bcs-api/processor/http/actions/v4http/storage/storage-actions.go
  bcs-services/bcs-dns/plugin/bcscustom/handler.go
  bcs-services/bcs-dns/plugin/bcscustom/metrics.go
  bcs-services/bcs-dns/plugin/bcsscheduler/events.go
  bcs-services/bcs-dns/plugin/bcsscheduler/handler.go
  bcs-services/bcs-dns/plugin/bcsscheduler/metrics.go
Labels: confirmed, enhancement, inner, service
