Repository TencentBlueKing/bk-bcs, pull requests merged in 2019-07, with the labels that each got.

#59 fix: adjust scripts in makefile, issue #57
  Makefile
Labels: confirmed, enhancement, inner

#62 首页readme调整
  README.md
  README_cn.md
  README_en.md
  bcs-services/bcs-loadbalance/bcs-statistic/statistic.md
Labels: confirmed, document, inner

#64 1.13.x分支定期合入
  Makefile
  README.md
  README_cn.md
  README_en.md
  bcs-services/bcs-loadbalance/bcs-statistic/statistic.md
Labels: bug, confirmed, document, enhancement, inner

#63 fix: 此方式导致某些情况下executor出现panic的情况，需要去掉check方法; issue #23
  bcs-mesos/bcs-container-executor/app/bcs_executor.go
Labels: bug, confirmed, inner

#69 优化readme
  README.md
Labels: confirmed, document, inner

#73 style: fix go vet issues in packages
  bcs-common/common/types/rc.go
  bcs-common/common/types/serverInfo.go
  bcs-common/common/types/service.go
  bcs-common/common/types/status.go
  bcs-mesos/bcs-mesos-driver/mesosdriver/mesosdriver.go
  bcs-mesos/bcs-scheduler/src/manager/store/framework.go
  bcs-mesos/bcs-scheduler/src/types/application.go
  bcs-services/bcs-api/processor/http/actions/v4http/clusterkeeper/cluster-actions.go
  bcs-services/bcs-api/processor/http/actions/v4http/k8s/k8s-actions.go
  bcs-services/bcs-api/processor/http/actions/v4http/mesos/mesos-actions.go
  bcs-services/bcs-api/processor/http/actions/v4http/metrics/metrics-actions.go
  bcs-services/bcs-api/processor/http/actions/v4http/netservice/netservice-actions.go
  bcs-services/bcs-api/processor/http/actions/v4http/storage/storage-actions.go
  bcs-services/bcs-health/doc/README.md
  bcs-services/bcs-health/pkg/healthz/type.go
  bcs-services/bcs-health/util/type.go
  bcs-services/bcs-metriccollector/pkg/collector/promparser_old.go
  bcs-services/bcs-metricservice/pkg/api/v1http/metric.go
  bcs-services/bcs-storage/storage/actions/v1http/alarms/alarms-action.go
  bcs-services/bcs-storage/storage/actions/v1http/cluster-config/clusterConfig-actions.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-k8s/dynamic-action.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-mesos/dynamic-action.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/dynamic-action.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-application.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-configmap-k8s.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-configmap.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-daemonset.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-deployment-k8s.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-deployment.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-endpoints-k8s.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-endpoints.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-exportservice.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-ingress.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-job.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-namespace.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-node.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-pod.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-process.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-replicaset.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-secret-k8s.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-secret.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-service-k8s.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-service.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-statefulset.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-taskgroup.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-watch/dynamic-action.go
  bcs-services/bcs-storage/storage/actions/v1http/events/events-action.go
  bcs-services/bcs-storage/storage/actions/v1http/host-config/hostConfig-action.go
  bcs-services/bcs-storage/storage/actions/v1http/metric-watch/metric-action.go
  bcs-services/bcs-storage/storage/actions/v1http/metric/metric-action.go
  bcs-services/bcs-storage/storage/actions/v1http/watch-k8s/watch-action.go
  bcs-services/bcs-storage/storage/actions/v1http/watch-mesos/watch-action.go
Labels: confirmed, enhancement, inner

#74 feature: add vet.sh for go vet check, issue #65
  scripts/vet.sh
Labels: confirmed, enhancement, inner

#75 feature: client list command support --all-namespaces options, issue #66
  bcs-services/bcs-client/cmd/list/agent.go
  bcs-services/bcs-client/cmd/list/application.go
  bcs-services/bcs-client/cmd/list/configmap.go
  bcs-services/bcs-client/cmd/list/deployment.go
  bcs-services/bcs-client/cmd/list/endpoint.go
  bcs-services/bcs-client/cmd/list/list.go
  bcs-services/bcs-client/cmd/list/namespace.go
  bcs-services/bcs-client/cmd/list/process.go
  bcs-services/bcs-client/cmd/list/secret.go
  bcs-services/bcs-client/cmd/list/service.go
  bcs-services/bcs-client/cmd/list/taskgroup.go
  bcs-services/bcs-client/cmd/utils/types.go
  bcs-services/bcs-client/cmd/utils/utils.go
  bcs-services/bcs-client/pkg/storage/v1/storage.go
  bcs-services/bcs-client/pkg/storage/v1/types.go
Labels: confirmed, feature, inner

#78 fix: go vet fix, issue #70
  bcs-services/bcs-dns/plugin/bcsscheduler/cache.go
  bcs-services/bcs-dns/plugin/bcsscheduler/lookup.go
  bcs-services/bcs-dns/plugin/bcsscheduler/scheduler.go
Labels: confirmed, enhancement, inner

#79 feature: add vet check and fmt in Makefile prework, issue #65
  Makefile
Labels: confirmed, enhancement, inner

#81 English version of BCS translation
  README_en.md
Labels: document, enhancement, outer

#84 docs: add practices & solutions doc, issue #83
  docs/features/practices/img/bcs-ci-example-distri.png
  docs/features/practices/通过BCS解决研发环境的资源复用.md
  docs/features/solutions/BCS跨云容器管理方案.md
  docs/features/solutions/img/bcs-global.png
Labels: confirmed, document, inner

#85 文档持续更新
  README.md
  docs/features/README.md
  docs/features/solutions/k8s-custom-scheduler.md
  docs/templates/mesos-artifact/application.md
Labels: confirmed, document, inner

#91 fix: fix bug that bcs-executor get runtime error; issue #88
  bcs-mesos/bcs-container-executor/network/cni/cni.go
Labels: bug, confirmed, inner

#92 Dev mars . docs: add rolling-update doc and blue-green-deploy doc; issue #83
  docs/features/practices/blue-green-deployment.md
  docs/features/practices/imgs/blue-green-deployment.png
  docs/features/practices/imgs/istio-architecture.png
  docs/features/practices/imgs/istio-mesos.png
  docs/features/practices/imgs/rolling-update.png
  docs/features/practices/rolling-update-howto.md
Labels: confirmed, document, inner

#94 发布1.13.3
  README.md
  README_en.md
  docs/features/mesos/基于mesos的容器编排.md
  docs/version/1.13.x.md
  docs/version/README.md
Labels: confirmed, inner

#100 fix: executor与mesos-slave长链接不设置timeout时间; issue #82
  bcs-mesos/bcs-container-executor/connection/connection.go
  bcs-mesos/bcs-container-executor/executor/executor.go
Labels: bug, confirmed, inner

#102 feature: add docker webconsole proxy for mesos cluster node, to suppo…
  .gitignore
  Makefile
  bcs-mesos/bcs-consoleproxy/app/app.go
  bcs-mesos/bcs-consoleproxy/app/options/options.go
  bcs-mesos/bcs-consoleproxy/console-proxy/api/api.go
  bcs-mesos/bcs-consoleproxy/console-proxy/config/config.go
  bcs-mesos/bcs-consoleproxy/console-proxy/manager/console.go
  bcs-mesos/bcs-consoleproxy/console-proxy/manager/interface.go
  bcs-mesos/bcs-consoleproxy/console-proxy/manager/manager.go
  bcs-mesos/bcs-consoleproxy/console-proxy/types/types.go
  bcs-mesos/bcs-consoleproxy/console-proxy/util/util.go
  bcs-mesos/bcs-consoleproxy/main.go
Labels: confirmed, feature, inner

#108 docs: add docs of stateful apps solution. issue #106
  docs/features/solutions/img/Operator工作管理.png
  docs/features/solutions/img/StatefulSet应用架构.png
  docs/features/solutions/img/etcd-operator代码示例.png
  docs/features/solutions/k8s有状态应用方案.md
Labels: confirmed, document, inner

#110 docs: add docs of how to develop a csi plugin. issue #109
  docs/features/solutions/img/CSI交互.png
  docs/features/solutions/img/CSI架构.png
  docs/features/solutions/img/CSI部署架构.png
  docs/features/solutions/如何编写一个csi存储插件.md
Labels: confirmed, document, inner

#111 增加CNI实践引导文档
  README.md
  README_en.md
  docs/features/solutions/cni-practise.md
  docs/overview/certificate.jpg
Labels: confirmed, document, inner

#114 fix: add paas_auth to bcs-api config template. issue #113
  install/cmd/conf/bcs-api/config_file.json.template
Labels: discussion, enhancement, inner

#117 docs: add docs of k8s container orchestration solution. issue #116
  README.md
  docs/features/k8s/image/bcs-api.png
  docs/features/k8s/基于k8s的容器编排.md
Labels: confirmed, document, inner

#118 CONTRIBUTING.md 有2处明显排版错误
  CONTRIBUTING.md
Labels: confirmed, document, outer

#120 fix: executor与mesos-slave长链接不设置timeout时间; issue #82
  bcs-mesos/bcs-container-executor/connection/connection.go
Labels: confirmed, enhancement, inner

#121 fix: 调整executor subcribe时间为1s; issue #82
  bcs-mesos/bcs-container-executor/executor/executor.go
Labels: bug, confirmed, inner
