Repository TencentBlueKing/bk-bcs, pull requests merged in 2019-12, with the labels that each got.

#289 1.15.x - webhook & logbeat-sidecar & service label & annotations
  bcs-common/common/types/endpoint.go
  bcs-mesos/bcs-mesos-driver/mesosdriver/backend/v4http/create.go
  bcs-mesos/bcs-mesos-watch/cluster/etcd/exportservice.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/exportservice.go
  bcs-mesos/bcs-scheduler/src/manager/sched/backend/admission-webhook.go
  bcs-mesos/bcs-scheduler/src/manager/sched/backend/command.go
  bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/service_mgr.go
  bcs-mesos/bcs-scheduler/src/manager/sched/strategy/strategy.go
  bcs-mesos/bcs-scheduler/src/manager/sched/task/task.go
  bcs-services/bcs-clb-controller/cmd/server.go
  bcs-services/bcs-clb-controller/pkg/clbingress/kube/clbingress.go
  bcs-services/bcs-clb-controller/pkg/cloudlb/qcloud/qcloudif/sdk/sdk.go
  bcs-services/bcs-clb-controller/pkg/processor/handler.go
  bcs-services/bcs-clb-controller/pkg/processor/status.go
  bcs-services/bcs-logbeat-sidecar/sidecar/controller.go
  bmsf-mesh/bmsf-mesos-adapter/pkg/util/str/string.go
  docs/templates/mesos-artifact/application.md
Labels: confirmed, enhancement, feature, inner, scheduler, service

#291 feature: add bcs-log-webhook-server to inject log config to container… #281
  Makefile
  bcs-mesos/bcs-consoleproxy/console-proxy/manager/console.go
  bcs-services/bcs-log-webhook-server/app/app.go
  bcs-services/bcs-log-webhook-server/config/config.go
  bcs-services/bcs-log-webhook-server/main.go
  bcs-services/bcs-log-webhook-server/options/options.go
  bcs-services/bcs-log-webhook-server/pkg/apis/bk-bcs/register.go
  bcs-services/bcs-log-webhook-server/pkg/apis/bk-bcs/v2/bcslogconfig_types.go
  bcs-services/bcs-log-webhook-server/pkg/apis/bk-bcs/v2/doc.go
  bcs-services/bcs-log-webhook-server/pkg/apis/bk-bcs/v2/register.go
  bcs-services/bcs-log-webhook-server/pkg/apis/bk-bcs/v2/zz_generated.deepcopy.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/clientset.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/doc.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/fake/clientset_generated.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/fake/doc.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/fake/register.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/scheme/doc.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/scheme/register.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/typed/bk-bcs/v2/bcslogconfig.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/typed/bk-bcs/v2/bk-bcs_client.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/typed/bk-bcs/v2/doc.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/typed/bk-bcs/v2/fake/doc.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/typed/bk-bcs/v2/fake/fake_bcslogconfig.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/typed/bk-bcs/v2/fake/fake_bk-bcs_client.go
  bcs-services/bcs-log-webhook-server/pkg/client/clientset/versioned/typed/bk-bcs/v2/generated_expansion.go
  bcs-services/bcs-log-webhook-server/pkg/client/informers/externalversions/bk-bcs/interface.go
  bcs-services/bcs-log-webhook-server/pkg/client/informers/externalversions/bk-bcs/v2/bcslogconfig.go
  bcs-services/bcs-log-webhook-server/pkg/client/informers/externalversions/bk-bcs/v2/interface.go
  bcs-services/bcs-log-webhook-server/pkg/client/informers/externalversions/factory.go
  bcs-services/bcs-log-webhook-server/pkg/client/informers/externalversions/generic.go
  bcs-services/bcs-log-webhook-server/pkg/client/informers/externalversions/internalinterfaces/factory_interfaces.go
  bcs-services/bcs-log-webhook-server/pkg/client/listers/bk-bcs/v2/bcslogconfig.go
  bcs-services/bcs-log-webhook-server/pkg/client/listers/bk-bcs/v2/expansion_generated.go
  bcs-services/bcs-log-webhook-server/pkg/inject/common.go
  bcs-services/bcs-log-webhook-server/pkg/inject/k8s_inject.go
  bcs-services/bcs-log-webhook-server/pkg/inject/mesos_inject.go
  bcs-services/bcs-log-webhook-server/pkg/inject/types.go
  docs/features/log-controller/bcs-log-webhook-server.md
  docs/features/log-controller/log-controller.md
  install/images/bcs-services/bcs-log-webhook-server/Dockerfile
  scripts/vet.sh
Labels: confirmed, feature, inner, service

#293 1.15.1-beta信息发布
  docs/version/1.14.x.md
  docs/version/1.15.x.md
  install/conf/bcs-mesos-master/bcs-scheduler/bcs-scheduler.json.template
  scripts/base.env
Labels: confirmed, document, inner

#294 1.15.1-beta发布
  docs/overview/bcs-architecture-v2.drawio
  docs/overview/bcs-architecture-v2.png
  install/conf/bcs-k8s-master/bcs-k8s-driver/bcs-k8s-driver.yaml.template
  install/conf/bcs-k8s-master/bcs-k8s-watch/bcs-k8s-watch.yaml.template
  install/conf/bcs-k8s-master/bcs-kube-agent/kube-agent.yaml
  scripts/base.env
Labels: confirmed, document, inner

#297 fix: mesos-watch同步exportservice数据时导致panic #296
  bcs-mesos/bcs-mesos-watch/cluster/etcd/app.go
  bcs-mesos/bcs-mesos-watch/cluster/etcd/exportservice.go
  bcs-mesos/bcs-mesos-watch/cluster/etcd/taskgroup.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/exportservice.go
  bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/service_mgr.go
Labels: confirmed, enhancement, inner, scheduler

#299 1.15.x信息发布
  Makefile
  docs/version/1.15.x.md
  install/cert/README.md
  install/conf/bcs-k8s-master/bcs-k8s-csi-tencentcloud/csi-cbsplugin-controller.yaml.template
  install/conf/bcs-k8s-master/bcs-k8s-csi-tencentcloud/csi-cbsplugin-node.yaml.template
  install/conf/bcs-k8s-master/bcs-k8s-custom-scheduler/bcs-k8s-custom-scheduler.manifest.template
  install/conf/bcs-k8s-master/bcs-k8s-driver/bcs-k8s-driver.yaml.template
  install/conf/bcs-k8s-master/bcs-k8s-driver/start.sh
  install/conf/bcs-k8s-master/bcs-k8s-watch/bcs-k8s-watch.json.template
  install/conf/bcs-k8s-master/bcs-k8s-watch/bcs-k8s-watch.yaml.template
  install/images/bcs-k8s-master/bcs-k8s-csi-tencentcloud/Dockerfile
  install/images/bcs-k8s-master/bcs-k8s-driver/Dockerfile
  install/images/bcs-k8s-master/bcs-k8s-watch/Dockerfile
  scripts/base.env
Labels: confirmed, document, inner

#301 docs: fix dockerfile position for pipeline, issue #292
  install/conf/bcs-k8s-master/bcs-k8s-csi-tencentcloud/Dockerfile
  install/conf/bcs-k8s-master/bcs-k8s-custom-scheduler/Dockerfile
  install/conf/bcs-k8s-master/bcs-k8s-driver/Dockerfile
  install/conf/bcs-k8s-master/bcs-k8s-watch/Dockerfile
  install/conf/bcs-k8s-master/bcs-kube-agent/Dockerfile
  install/conf/bcs-mesos-node/bcs-metriccollector/Dockerfile
  install/conf/bcs-services/bcs-loadbalance/Dockerfile
  install/conf/bcs-services/bcs-log-webhook-server/Dockerfile
Labels: confirmed, document, inner

#302 fix: fix watch dockerfile, issue #292
  install/conf/bcs-k8s-master/bcs-k8s-watch/Dockerfile
Labels: confirmed, document, inner

#303 fix: watch cert, issue #292
  install/conf/bcs-k8s-master/bcs-k8s-watch/Dockerfile
Labels: confirmed, inner

#312 1.15.x 容器自定义command命令，image支持模糊匹配;
  bcs-common/pkg/module-discovery/mesos-discovery.go
  bcs-mesos/bcs-scheduler/src/manager/sched/backend/command.go
Labels: confirmed, feature, inner, scheduler

#314 Loadbalance优化
  bcs-services/bcs-clb-controller/pkg/processor/handler.go
  bcs-services/bcs-clb-controller/pkg/processor/processor.go
  bcs-services/bcs-loadbalance/main.go
  bcs-services/bcs-loadbalance/template/haproxy/haproxy.go
  docs/features/bcs-clb-controller/deploy/helm/clb-controller/values.yaml
  docs/features/bcs-clb-controller/deploy/helm/clb-ingress/values.yaml
Labels: confirmed, enhancement, inner, service

#317 文档风格调整
  README.md
  README_en.md
  docs/logo/bcs_zh_v2.png
Labels: document, inner

#316 support netservice ip resource details query actions. issue #315
  bcs-k8s/bcs-k8s-watch/app/k8s/manager.go
  bcs-k8s/bcs-k8s-watch/app/k8s/watcher.go
  bcs-mesos/bcs-mesos-watch/cluster/etcd/cluster.go
  bcs-mesos/bcs-mesos-watch/cluster/etcd/netservice.go
  bcs-mesos/bcs-mesos-watch/cluster/mesos/mesos.go
  bcs-mesos/bcs-mesos-watch/cluster/metric.go
  bcs-mesos/bcs-mesos-watch/storage/cc.go
  bcs-mesos/bcs-mesos-watch/storage/metrics.go
  bcs-mesos/bcs-mesos-watch/storage/netservice.go
  bcs-services/bcs-client/cmd/get/get.go
  bcs-services/bcs-client/pkg/storage/v1/storage.go
  bcs-services/bcs-client/pkg/storage/v1/types.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/dynamic-action.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic-query/filter-ippoolstatic-detail.go
Labels: confirmed, enhancement, inner, service

#320 fix: fix bcs-loadbalance panic error which is caused by metric collec…
  bcs-services/bcs-loadbalance/app/reflector.go
  bcs-services/bcs-loadbalance/image/config/haproxy.cfg
  bcs-services/bcs-loadbalance/image/start.sh
  bcs-services/bcs-loadbalance/template/haproxy/exporter.go
Labels: bug, confirmed, enhancement, inner, network

#323 格式调整
  LICENSE.txt
Labels: confirmed, document

#324 1.15.x
  LICENSE.txt
Labels: confirmed, document
