Repository TencentBlueKing/bk-bcs, pull requests merged in 2020-03, with the labels that each got.

#390 feature: adjust some code. issue #376
  bcs-k8s/bcs-kube-agent/app/report.go
  bcs-k8s/bcs-kube-agent/main.go
Labels: confirmed, enhancement, inner, service

#392 fix: add license; issue #340
  bcs-services/bcs-gw-controller/pkg/gw/mock_client.go
Labels: confirmed, inner

#394 docs: release 1.16.1-alpha, issue #388
  docs/version/1.15.x.md
  docs/version/1.16.x.md
  docs/version/README.md
Labels: confirmed, document, inner

#402 fix: fix startup parameter, issue #388
  bcs-k8s/bcs-k8s-driver/kubedriver/custom/clusterresource.go
  bcs-k8s/bcs-k8s-driver/kubedriver/options/options.go
  install/conf/bcs-k8s-master/bcs-k8s-driver/Dockerfile
  install/conf/bcs-k8s-master/bcs-k8s-driver/bcs-k8s-driver.yaml.template
  install/conf/bcs-k8s-master/bcs-k8s-driver/start.sh
  install/conf/bcs-k8s-master/bcs-k8s-watch/bcs-k8s-watch.json.template
  install/conf/bcs-k8s-master/bcs-kube-agent/kube-agent.yaml
  scripts/base.env
Labels: confirmed, inner

#404 fix: fix lint warning; issue #144
  bcs-services/bcs-clb-controller/pkg/processor/updater.go
Labels: confirmed, inner

#401 fix: bcs-webhook-server append envs to container instead of override.…
  bcs-services/bcs-webhook-server/pkg/inject/k8s/log_conf.go
  bcs-services/bcs-webhook-server/pkg/inject/mesos/log_conf.go
Labels: bug, confirmed, inner

#405 1.16.x
  bcs-k8s/bcs-kube-agent/app/report.go
Labels: bug, confirmed, inner

#408 feature: 调整mesos version对象的命名规则 #383
  bcs-mesos/bcs-scheduler/src/manager/store/etcd/version.go
Labels: bug, confirmed, inner, scheduler

#409 feature: 调整mesos version对象的命名规则 #383
  bcs-mesos/bcs-scheduler/src/manager/store/etcd/version.go
Labels: bug, confirmed, inner, scheduler

#411 docs: update 1.15.x & 1.16.x version, issue #383
  docs/version/1.15.x.md
  docs/version/1.16.x.md
Labels: confirmed, inner

#418 feature: add network policy; issue #417
  Makefile
  bcs-services/bcs-networkpolicy/controller/ipset.go
  bcs-services/bcs-networkpolicy/controller/networkpolicy.go
  bcs-services/bcs-networkpolicy/controller/node.go
  bcs-services/bcs-networkpolicy/controller/node_test.go
  bcs-services/bcs-networkpolicy/datainformer/interface.go
  bcs-services/bcs-networkpolicy/datainformer/kubernetes/kubernetes.go
  bcs-services/bcs-networkpolicy/datainformer/mesos/mesos.go
  bcs-services/bcs-networkpolicy/main.go
  bcs-services/bcs-networkpolicy/metrics/metrics.go
  bcs-services/bcs-networkpolicy/options/options.go
  bcs-services/bcs-networkpolicy/server/server.go
  install/conf/bcs-services/bcs-networkpolicy/Dockerfile
Labels: confirmed, feature, inner, network
