Repository TencentBlueKing/bk-bcs, pull requests merged in 2020-05, with the labels that each got.

#451 fix: etcd存储下save taskgroup偶尔会失败 #436
  bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/trans_command.go
  bcs-mesos/bcs-scheduler/src/types/application.go
Labels: bug, confirmed, inner, mesos, scheduler

#453 发布1.16.4
  docs/version/1.16.x.md
  docs/version/README.md
Labels: confirmed, document, inner

#459 1.17.1-alpha发布
  Makefile
  docs/version/1.17.x.md
  docs/version/README.md
Labels: document, inner

#461 add docs of 1.17.x
  docs/apidoc/api.md
  docs/apidoc/bcs-user-manager.md
  docs/apidoc/k8s.md
  docs/features/bcs-client/bcs-client_HANDBOOK.md
  docs/features/bcs-client/picture/create-user.png
  docs/features/bcs-client/picture/exec-into-taskgroup.png
  docs/features/bcs-client/picture/grant-permission.png
  docs/features/bcs-client/picture/refresh-plain-user.png
  docs/features/bcs-client/picture/refresh-saas-user.png
  docs/features/bcs-client/picture/revoke-permission.png
  docs/features/k8s/基于k8s的容器编排.md
Labels: confirmed, document, inner

#465 feature: 调整kube-apiserver访问的ratelimiter #462
  bcs-mesos/bcs-scheduler/src/manager/store/etcd/store.go
  bcs-mesos/bcs-scheduler/src/manager/store/etcd/taskgroup.go
Labels: confirmed, inner, mesos, scheduler

#466 增加bcs-gateway-discovery编译部署
  Makefile
Labels: confirmed, inner, service
