Repository TencentBlueKing/bk-bcs, pull requests merged in 2020-08, with the labels that each got.

#542 feature: mesos方案支持Daemonset特性 #207
  bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/daemonset.go
Labels: confirmed, feature, inner, mesos

#544 featrue: mesos方案优化scheduler metrics数据 #532
  bcs-mesos/bcs-migrate-data/main.go
Labels: bug, confirmed, inner

#545 1.18.3 release
  Makefile
  bcs-common/common/RegisterDiscover/zkregdiscv.go
  bcs-common/common/types/rc.go
  bcs-common/pkg/mesosdriver/client.go
  bcs-k8s/bcs-egress/go.sum
  bcs-k8s/bcs-gamestatefulset-operator/doc/deploy/01-resources.yaml
  bcs-k8s/bcs-gamestatefulset-operator/doc/deploy/03-rbac.yaml
  bcs-mesos/bcs-mesos-driver/mesosdriver/backend/v4http/create.go
  bcs-mesos/bcs-mesos-driver/mesosdriver/backend/v4http/customresource.go
  bcs-mesos/bcs-scheduler/src/manager/sched/offer/offerpool.go
  bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/daemonset.go
  bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/data_check.go
  bcs-mesos/bcs-scheduler/src/manager/sched/scheduler/scheduler.go
  bcs-mesos/bcs-scheduler/src/manager/sched/task/task.go
  bcs-mesos/bcs-scheduler/src/manager/store/etcd/store.go
  bcs-mesos/bcs-scheduler/src/manager/store/etcd/task.go
  bcs-mesos/bcs-scheduler/src/manager/store/etcd/taskgroup.go
  bcs-mesos/bcs-scheduler/src/manager/store/zk/store.go
  bcs-mesos/pkg/apis/monitor/v1/servicemonitor_types.go
  bcs-services/bcs-clb-controller/pkg/qcloud/meta.go
  bcs-services/bcs-network-detection/app/app.go
  bcs-services/bcs-network-detection/network-detection/network-detection.go
  bcs-services/bcs-service-prometheus/app/options/options.go
  bcs-services/bcs-service-prometheus/config/config.go
  bcs-services/bcs-service-prometheus/discovery/node-etcd-discovery.go
  bcs-services/bcs-service-prometheus/discovery/service-monitor.go
  bmsf-configuration/cmd/bscp-bcs-sidecar/service/puller.go
  docs/features/bcs-api-gateway/api-gateway方案.md
  docs/specification/go-micro.md
  docs/specification/license-header.txt
  docs/version/1.18.x.md
  docs/version/README.md
  go.mod
  go.sum
  install/conf/bcs-k8s-master/bcs-k8s-watch/bcs-k8s-watch.json.template
  install/patch/nginx-1.15.8-http2-spdy.patch
Labels: confirmed, document, inner

#547 1.18.3 DNS编译
  Makefile
  install/conf/bcs-services/bcs-dns-service/container-start.sh
Labels: confirmed, document, inner

#555 Feature fixed ip
  bcs-network/bcs-cloud-netagent/cmd/bcs-eni-ipam/main.go
Labels: confirmed, inner, network

#558 1.18.x社区版本镜像流水线构建调整
  install/conf/bcs-k8s-master/bcs-k8s-watch/bcs-k8s-watch.json.template
  install/conf/bcs-services/bcs-gateway-discovery/kong.conf.template
Labels: confirmed, document, enhancement, inner
