Repository TencentBlueKing/bk-bcs, pull requests merged in 2020-07, with the labels that each got.

#511 fix: fix a little bug of bcs-api websocket tunnel. issue #510
  bcs-services/bcs-api/tunnel/peermanager.go
Labels: bug, confirmed, inner, k8s

#512 fix: fix a little bug of bcs-api websocket tunnel. issue #510
  bcs-services/bcs-api/tunnel/peermanager.go
Labels: confirmed, inner, k8s

#513 1.18.1-alpha
  bcs-k8s/bcs-gamestatefulset-operator/go.sum
  bcs-k8s/bcs-k8s-watch/app/k8s/synchronizer.go
  bcs-k8s/bcs-k8s-watch/app/k8s/watcher.go
  docs/version/1.17.x.md
  docs/version/1.18.x.md
  docs/version/README.md
  install/conf/Dockerfile
  install/conf/bcs-k8s-master/bcs-cc-agent/Dockerfile
  install/conf/bcs-k8s-master/bcs-cc-agent/container-start.sh
  install/conf/container-start.sh
Labels: confirmed, inner

#516 chore: change information for community pipeline, issue #508
  bcs-mesos/bcs-mesos-driver/mesosdriver/backend/v4http/scheduler-api.go
  bcs-mesos/bcs-scheduler/src/manager/sched/api/api.go
  bcs-mesos/bcs-scheduler/src/manager/sched/backend/agent_setting.go
  bcs-mesos/bcs-scheduler/src/manager/sched/offer/offerpool.go
  bcs-services/bcs-logbeat-sidecar/sidecar/controller.go
  docs/features/bcs-api-gateway/api-gateway方案.md
  docs/specification/dockerfile-spec.md
  docs/version/1.15.x.md
  install/conf/Dockerfile
  install/conf/bcs-k8s-master/bcs-cc-agent/Dockerfile
  install/conf/bcs-k8s-master/bcs-egress-controller/Dockerfile
  install/conf/bcs-k8s-master/bcs-gamestatefulset-operator/Dockerfile
  install/conf/bcs-k8s-master/bcs-k8s-csi-tencentcloud/Dockerfile
  install/conf/bcs-k8s-master/bcs-k8s-custom-scheduler/Dockerfile
  install/conf/bcs-k8s-master/bcs-k8s-driver/Dockerfile
  install/conf/bcs-k8s-master/bcs-k8s-watch/Dockerfile
  install/conf/bcs-k8s-master/bcs-kube-agent/Dockerfile
  install/conf/bcs-mesos-node/bcs-metriccollector/Dockerfile
  install/conf/bcs-services/bcs-api/Dockerfile
  install/conf/bcs-services/bcs-clb-controller/Dockerfile
  install/conf/bcs-services/bcs-client/Dockerfile
  install/conf/bcs-services/bcs-client/bcs.conf.template
  install/conf/bcs-services/bcs-cloud-network-agent/Dockerfile
  install/conf/bcs-services/bcs-dns-service/Dockerfile
  install/conf/bcs-services/bcs-gateway-discovery/Dockerfile
  install/conf/bcs-services/bcs-gateway-discovery/container-start.sh
  install/conf/bcs-services/bcs-gateway-discovery/kong.conf.template
  install/conf/bcs-services/bcs-gw-controller/Dockerfile
  install/conf/bcs-services/bcs-logbeat-sidecar/Dockerfile
  install/conf/bcs-services/bcs-netservice/Dockerfile
  install/conf/bcs-services/bcs-network-detection/Dockerfile
  install/conf/bcs-services/bcs-networkpolicy/Dockerfile
  install/conf/bcs-services/bcs-service-prometheus-service/Dockerfile
  install/conf/bcs-services/bcs-storage/Dockerfile
  install/conf/bcs-services/bcs-storage/container-start.sh
  install/conf/bcs-services/bcs-user-manager/Dockerfile
  install/conf/bcs-services/bcs-webhook-server/Dockerfile
Labels: confirmed, document, inner

#518 1.18.x qcloud eip fix
  bcs-services/bcs-network/qcloud-eip/conf/conf.go
  bcs-services/bcs-network/qcloud-eip/eip/eip.go
  bcs-services/bcs-network/qcloud-eip/eip/instance.go
  bcs-services/bcs-network/qcloud-eip/eip/netservice.go
  bcs-services/bcs-network/qcloud-eip/eip/util.go
  bcs-services/bcs-network/qcloud-eip/eip/vpc.go
Labels: bug, confirmed, inner, k8s, service

#517 1.17.x qcloud eip fix
  bcs-services/bcs-network/qcloud-eip/conf/conf.go
  bcs-services/bcs-network/qcloud-eip/eip/eip.go
  bcs-services/bcs-network/qcloud-eip/eip/instance.go
  bcs-services/bcs-network/qcloud-eip/eip/netservice.go
  bcs-services/bcs-network/qcloud-eip/eip/util.go
  bcs-services/bcs-network/qcloud-eip/eip/vpc.go
Labels: bug, confirmed, inner, k8s, network

#520 fix: mesos 1.17.x版本resources.limit不生效 #519
  bcs-mesos/bcs-mesos-driver/mesosdriver/backend/v4http/create.go
Labels: confirmed, inner, mesos

#524 1.18.2-alpha
  Makefile
  bcs-k8s/bcs-gamestatefulset-operator/README.md
  bcs-k8s/bcs-gamestatefulset-operator/doc/deploy/03-rbac.yaml
  bcs-k8s/bcs-gamestatefulset-operator/doc/deploy/04-operator-deployment.yaml
  bcs-services/bcs-gateway-discovery/app/options.go
  bcs-services/bcs-gateway-discovery/app/server.go
  docs/features/bcs-api-gateway/api-gateway方案.md
  docs/version/1.18.x.md
  docs/version/README.md
  install/conf/Dockerfile
  install/conf/bcs-k8s-master/bcs-cc-agent/Dockerfile
  install/conf/bcs-k8s-master/bcs-cc-agent/container-start.sh
  install/conf/bcs-k8s-master/bcs-egress-controller/Dockerfile
  install/conf/bcs-k8s-master/bcs-egress-controller/container-start.sh
  install/conf/bcs-k8s-master/bcs-gamestatefulset-operator/Dockerfile
  install/conf/bcs-k8s-master/bcs-k8s-driver/Dockerfile
  install/conf/bcs-k8s-master/bcs-k8s-watch/Dockerfile
  install/conf/bcs-k8s-master/bcs-k8s-watch/bcs-k8s-watch.json.template
  install/conf/bcs-k8s-master/bcs-k8s-watch/container-start.sh
  install/conf/bcs-k8s-master/bcs-kube-agent/Dockerfile
  install/conf/bcs-k8s-master/bcs-kube-agent/kube-agent-secret.yml
  install/conf/bcs-services/bcs-api/Dockerfile
  install/conf/bcs-services/bcs-api/container-start.sh
  install/conf/bcs-services/bcs-clb-controller/Dockerfile
  install/conf/bcs-services/bcs-client/Dockerfile
  install/conf/bcs-services/bcs-cloud-network-agent/Dockerfile
  install/conf/bcs-services/bcs-cloud-network-agent/container-start.sh
  install/conf/bcs-services/bcs-dns-service/Dockerfile
  install/conf/bcs-services/bcs-dns-service/container-start.sh
  install/conf/bcs-services/bcs-gateway-discovery/Dockerfile
  install/conf/bcs-services/bcs-gateway-discovery/container-start.sh
  install/conf/bcs-services/bcs-gateway-discovery/kong.conf.template
  install/conf/bcs-services/bcs-gw-controller/Dockerfile
  install/conf/bcs-services/bcs-gw-controller/container-start.sh
  install/conf/bcs-services/bcs-logbeat-sidecar/Dockerfile
  install/conf/bcs-services/bcs-logbeat-sidecar/container-start.sh
  install/conf/bcs-services/bcs-netservice/Dockerfile
  install/conf/bcs-services/bcs-netservice/container-start.sh
  install/conf/bcs-services/bcs-network-detection/Dockerfile
  install/conf/bcs-services/bcs-network-detection/container-start.sh
  install/conf/bcs-services/bcs-networkpolicy/Dockerfile
  install/conf/bcs-services/bcs-networkpolicy/container-start.sh
  install/conf/bcs-services/bcs-service-prometheus-service/Dockerfile
  install/conf/bcs-services/bcs-service-prometheus-service/container-start.sh
  install/conf/bcs-services/bcs-storage/Dockerfile
  install/conf/bcs-services/bcs-storage/container-start.sh
  install/conf/bcs-services/bcs-user-manager/Dockerfile
  install/conf/bcs-services/bcs-user-manager/container-start.sh
  install/conf/bcs-services/bcs-webhook-server/Dockerfile
  install/conf/bcs-services/bcs-webhook-server/container-start.sh
  install/conf/container-start.sh
  scripts/env.sh
Labels: confirmed, inner

#529 feature: statefulset支持多端口映射
  bcs-services/bcs-clb-controller/pkg/apis/clb/v1/clbingress_types.go
  bcs-services/bcs-clb-controller/pkg/processor/updater.go
  docs/features/bcs-clb-controller/README.md
Labels: confirmed, feature, inner, k8s, network
