Repository TencentBlueKing/bk-bcs, pull requests merged in 2021-05, with the labels that each got.

#870 feature: optimize bcs-ingress-controller cloud api calls; issue #864
  bcs-mesos/bcs-container-executor/devicepluginmanager/resource_manager_test.go
  bcs-network/bcs-ingress-controller/internal/cloud/interface.go
  bcs-network/bcs-ingress-controller/internal/cloud/mock/mockcloud.go
  bcs-network/bcs-ingress-controller/internal/cloud/nstencentcloud/namespacedclient.go
  bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/api.go
  bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/clb.go
  bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/constant.go
  bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/helper.go
  bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/helperbatch.go
  bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/sdk.go
  bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/util.go
  bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/util_test.go
  bcs-network/bcs-ingress-controller/internal/cloud/tencentcloud/validate.go
  bcs-network/bcs-ingress-controller/internal/constant/constant.go
  bcs-network/bcs-ingress-controller/internal/generator/conflict.go
  bcs-network/bcs-ingress-controller/internal/generator/ingressconverter.go
  bcs-network/bcs-ingress-controller/internal/generator/ingressconverter_test.go
  bcs-network/bcs-ingress-controller/internal/generator/mappingconverter.go
  bcs-network/bcs-ingress-controller/internal/generator/ruleconverter.go
  bcs-network/bcs-ingress-controller/internal/option/option.go
  bcs-network/bcs-ingress-controller/internal/worker/cache.go
  bcs-network/bcs-ingress-controller/internal/worker/event.go
  bcs-network/bcs-ingress-controller/internal/worker/event_test.go
  bcs-network/bcs-ingress-controller/internal/worker/options.go
  bcs-network/bcs-ingress-controller/internal/worker/synchronizer.go
  bcs-network/bcs-ingress-controller/internal/worker/synchronizer_test.go
  bcs-network/bcs-ingress-controller/internal/worker/util.go
  bcs-network/bcs-ingress-controller/listenercontroller/listener_controller.go
  bcs-network/bcs-ingress-controller/main.go
  bcs-network/go.mod
Labels: confirmed, feature, inner, network

#878 fix bcs-k8s-watch init config & bcs-alert-manager adapt alert
  bcs-k8s/bcs-k8s-watch/app/app.go
  bcs-k8s/bcs-k8s-watch/app/options/options.go
  bcs-k8s/bcs-k8s-watch/main.go
  bcs-services/bcs-alert-manager/pkg/handler/eventhandler/handler.go
  bcs-services/bcs-alert-manager/pkg/remote/alert/alert_test.go
  bcs-services/bcs-alert-manager/pkg/server/actions/alert.go
  install/conf/bcs-k8s-master/bcs-k8s-watch/bcs-k8s-watch.json.template
Labels: confirmed, feature, inner

#879 Fix/gamestatefulset pod forcedelete nodelost
  bcs-k8s/bcs-gamestatefulset-operator/cmd/gamestatefulset-operator/main.go
  bcs-k8s/bcs-gamestatefulset-operator/pkg/controllers/game_stateful_set.go
  bcs-k8s/bcs-gamestatefulset-operator/pkg/controllers/game_stateful_set_control.go
  bcs-k8s/bcs-gamestatefulset-operator/pkg/controllers/gamestatefulset_pod_control.go
  docs/features/bcs-gamestatefulset-operator/README.md
  install/helm/bcs-gamestatefulset-operator/templates/2-crd.yaml
  install/helm/bcs-gamestatefulset-operator/templates/3-clusterrole.yaml
Labels: bug, inner

#882 feature: add transaction into scheduler types; issue #881
  bcs-common/go.mod
  bcs-common/pkg/scheduler/schetypes/container.go
  bcs-common/pkg/scheduler/schetypes/message.go
  bcs-common/pkg/scheduler/schetypes/transaction.go
  bcs-common/pkg/scheduler/schetypes/utils.go
Labels: confirmed, feature, inner, mesos, service

#886 feature: bcs-common/pkg/msgqueue support custom queuename issue #884
  bcs-common/pkg/msgqueue/queue.go
Labels: confirmed, inner, service

#885 fix: bcs-logbeat-sidecar hangs forever. fix #883
  bcs-services/bcs-logbeat-sidecar/sidecar/cache.go
  bcs-services/bcs-logbeat-sidecar/sidecar/controller.go
Labels: bug, confirmed, inner, service

#891 bcslogconfigs 定义添加PodNamePattern字段，以支持logbeat-sidecar的静态pod日志采集需求
  bcs-k8s/kubebkbcs/apis/bkbcs/v1/bcslogconfig_types.go
Labels: confirmed, feature, inner, service

#895 docs: add mesos ingress api docs; issue #894
  docs/apidoc/api-mesos-ingress.md
Labels: confirmed, document, inner

#897 bcs-client 文档更新
  docs/features/bcs-client/bcs-client_HANDBOOK.md
  docs/features/bcs-client/img/add.png
  docs/features/bcs-client/img/get.png
Labels: confirmed, document, inner

#900 fix: modify duplicated key judgement for mongo driver; issue #899
  bcs-common/pkg/odm/drivers/err.go
  bcs-common/pkg/odm/drivers/mongo/mongo.go
Labels: confirmed, inner, service

#901 fix: fix clusterops error when multiple master node in one cluster; issue #898 #899
  bcs-services/bcs-cluster-manager/go.mod
  bcs-services/bcs-cluster-manager/internal/actions/namespace/createquota.go
  bcs-services/bcs-cluster-manager/internal/actions/namespacequota/create.go
  bcs-services/bcs-cluster-manager/internal/clusterops/clusterclient.go
Labels: bug, confirmed, inner, service

#905 feature: change cluster manager return code to digital, add region to quota info; issue #904
  bcs-services/bcs-cluster-manager/api/clustermanager/clustermanager.pb.go
  bcs-services/bcs-cluster-manager/api/clustermanager/clustermanager.pb.validate.go
  bcs-services/bcs-cluster-manager/api/clustermanager/clustermanager.proto
  bcs-services/bcs-cluster-manager/api/clustermanager/clustermanager.swagger.json
  bcs-services/bcs-cluster-manager/internal/actions/cluster/create.go
  bcs-services/bcs-cluster-manager/internal/actions/cluster/delete.go
  bcs-services/bcs-cluster-manager/internal/actions/cluster/federatecluster.go
  bcs-services/bcs-cluster-manager/internal/actions/cluster/get.go
  bcs-services/bcs-cluster-manager/internal/actions/cluster/list.go
  bcs-services/bcs-cluster-manager/internal/actions/cluster/update.go
  bcs-services/bcs-cluster-manager/internal/actions/clustercredential/delete.go
  bcs-services/bcs-cluster-manager/internal/actions/clustercredential/get.go
  bcs-services/bcs-cluster-manager/internal/actions/clustercredential/list.go
  bcs-services/bcs-cluster-manager/internal/actions/clustercredential/update.go
  bcs-services/bcs-cluster-manager/internal/actions/namespace/create.go
  bcs-services/bcs-cluster-manager/internal/actions/namespace/createquota.go
  bcs-services/bcs-cluster-manager/internal/actions/namespace/delete.go
  bcs-services/bcs-cluster-manager/internal/actions/namespace/get.go
  bcs-services/bcs-cluster-manager/internal/actions/namespace/list.go
  bcs-services/bcs-cluster-manager/internal/actions/namespace/update.go
  bcs-services/bcs-cluster-manager/internal/actions/namespacequota/create.go
  bcs-services/bcs-cluster-manager/internal/actions/namespacequota/delete.go
  bcs-services/bcs-cluster-manager/internal/actions/namespacequota/get.go
  bcs-services/bcs-cluster-manager/internal/actions/namespacequota/list.go
  bcs-services/bcs-cluster-manager/internal/actions/namespacequota/update.go
  bcs-services/bcs-cluster-manager/internal/types/types.go
Labels: bug, confirmed, inner, service

#893 [logbeat-sidecar] static pod log collection
  bcs-services/bcs-clb-controller/go.mod
  bcs-services/bcs-logbeat-sidecar/go.mod
  bcs-services/bcs-logbeat-sidecar/sidecar/controller.go
  bcs-services/bcs-logbeat-sidecar/sidecar/logconfig.go
  go.mod
Labels: confirmed, feature, inner, service

#903 [docs] Change docs/overview documentation, version of v1.21.x
  docs/overview/README.md
  docs/overview/architecture.md
  docs/overview/bcs-ar-open.png
  docs/overview/bcs-architecture-v3.drawio
  readme_en.md
Labels: confirmed, document, inner
