Repository TencentBlueKing/bk-bcs, pull requests merged in 2021-01, with the labels that each got.

#717 信息修复
  .code.yml
  bcs-services/bcs-api/auth/bkiam/auth.go
  go.mod
  go.sum
Labels: confirmed, inner

#716 db授权支持配置operator
  bcs-services/bcs-webhook-server/internal/plugin/dbprivilege/dbprivilege.go
  bcs-services/bcs-webhook-server/pkg/apis/bk-bcs/v1/db_priv_config.go
Labels: feature, inner, service

#714 Fix bcs webhook server
  bcs-k8s/kubernetes/apis/cloud/v1/nodenetwork_types.go
  bcs-k8s/kubernetes/config/crd/bases/cloud.bkbcs.tencent.com_nodenetworks.yaml
  bcs-services/bcs-webhook-server/internal/plugin/bcslog/bcslog.go
  bcs-services/bcs-webhook-server/internal/plugin/bscp/bscp.go
  bcs-services/bcs-webhook-server/internal/plugin/dbprivilege/dbprivilege.go
  bcs-services/bcs-webhook-server/internal/plugin/fake/fake.go
  bcs-services/bcs-webhook-server/internal/pluginutil/pluginutil.go
  bcs-services/bcs-webhook-server/internal/server/k8s.go
  install/conf/bcs-network/bcs-cloud-network-agent/Dockerfile
Labels: bug, confirmed, inner, service

#727 fix: change bk-bcs dependency from local to v1.20.0; issue #722
  bcs-k8s/bcs-gamedeployment-operator/go.mod
  bcs-k8s/bcs-gamestatefulset-operator/go.mod
  bcs-k8s/bcs-hook-operator/go.mod
  bcs-k8s/bcs-k8s-driver/go.mod
  bcs-k8s/bcs-k8s-watch/go.mod
  bcs-k8s/kubedeprecated/go.mod
  bcs-mesos/kubebkbcsv2/go.mod
  bcs-mesos/mesosv2/go.mod
  bcs-network/go.mod
  bcs-services/bcs-client/go.mod
  bcs-services/bcs-log-manager/go.mod
  bcs-services/bcs-logbeat-sidecar/go.mod
  bcs-services/bcs-mesh-manager/go.mod
  bcs-services/bcs-webhook-server/go.mod
  go.mod
Labels: confirmed, inner

#726 feature: support configuring logbeat's package option
  bcs-k8s/kubebkbcs/apis/bk-bcs/v1/bcslogconfig_types.go
  bcs-services/bcs-logbeat-sidecar/sidecar/controller.go
  bcs-services/bcs-logbeat-sidecar/types/types.go
Labels: confirmed, feature, inner

#734 Feature: build global msgqueue(rabbitmq/nats-streaming)
  bcs-common/go.mod
  bcs-common/pkg/msgqueue/broker.go
  bcs-common/pkg/msgqueue/filter.go
  bcs-common/pkg/msgqueue/handler.go
  bcs-common/pkg/msgqueue/options.go
  bcs-common/pkg/msgqueue/queue.go
  bcs-common/pkg/msgqueue/queue_test.go
  bcs-services/bcs-logbeat-sidecar/go.mod
  go.sum
Labels: confirmed, feature, inner, service

#735 bcs-api-gateway feature
  .code.yml
  Makefile
  bcs-common/pkg/esb/client/request.go
  bcs-common/pkg/service/signal.go
  bcs-k8s/bcs-k8s-watch/README.md
  bcs-k8s/bcs-k8s-watch/app/app.go
  bcs-k8s/bcs-k8s-watch/app/bcs/cluster.go
  bcs-k8s/bcs-k8s-watch/app/bcs/service.go
  bcs-k8s/bcs-k8s-watch/app/healthz.go
  bcs-k8s/bcs-k8s-watch/app/options/options.go
  bcs-k8s/bcs-k8s-watch/main.go
  bcs-services/bcs-gateway-discovery/app/micro.go
  bcs-services/bcs-gateway-discovery/app/options.go
  bcs-services/bcs-gateway-discovery/app/server.go
  bcs-services/bcs-gateway-discovery/app/zookeeper.go
  bcs-services/bcs-gateway-discovery/main.go
  bcs-services/bcs-gateway-discovery/plugins/apisix/bkbcs-auth.lua
  bcs-services/bcs-gateway-discovery/plugins/apisix/bkbcs-auth/bkbcs.lua
  bcs-services/bcs-gateway-discovery/plugins/kong/bkbcs-auth/bkbcs.lua
  bcs-services/bcs-gateway-discovery/plugins/kong/bkbcs-auth/handler.lua
  bcs-services/bcs-gateway-discovery/plugins/kong/bkbcs-auth/schema.lua
  bcs-services/bcs-gateway-discovery/register/apisix/admin/api.go
  bcs-services/bcs-gateway-discovery/register/apisix/admin/client.go
  bcs-services/bcs-gateway-discovery/register/apisix/admin/types.go
  bcs-services/bcs-gateway-discovery/register/apisix/api.go
  bcs-services/bcs-gateway-discovery/register/apisix/apisix.go
  bcs-services/bcs-gateway-discovery/register/apisix/apisix_test.go
  bcs-services/bcs-gateway-discovery/register/kong/kong.go
  bcs-services/bcs-gateway-discovery/register/register.go
  bcs-services/bcs-gateway-discovery/register/types.go
  bcs-services/bcs-user-manager/app/user-manager/v1http/auth.go
  bcs-services/bcs-user-manager/app/user-manager/v1http/cluster.go
  bcs-services/bcs-user-manager/app/user-manager/v1http/credentials.go
  bcs-services/bcs-user-manager/app/user-manager/v1http/permission.go
  bcs-services/bcs-user-manager/app/user-manager/v1http/register-token.go
  docs/features/bcs-api-gateway/api-gateway方案.md
  docs/specification/go-micro.md
  docs/version/1.18.x.md
  go.mod
  go.sum
  install/conf/bcs-k8s-master/bcs-k8s-watch/bcs-k8s-watch.json.template
  install/conf/bcs-k8s-master/bcs-kube-agent/kube-agent.yaml
  install/conf/bcs-services/bcs-gateway-discovery/Dockerfile
  install/conf/bcs-services/bcs-gateway-discovery/Dockerfile.apisix
  install/conf/bcs-services/bcs-gateway-discovery/Dockerfile.gateway
  install/conf/bcs-services/bcs-gateway-discovery/apisix-2.1-0.el7.noarch.rpm
  install/conf/bcs-services/bcs-gateway-discovery/apisix-start.sh
  install/conf/bcs-services/bcs-gateway-discovery/bcs-gateway-discovery.json.template
  install/conf/bcs-services/bcs-gateway-discovery/config.yaml.template
  install/conf/bcs-services/bcs-gateway-discovery/kong.conf.template
  install/conf/bcs-services/bcs-storage/bcs-storage.json.template
  install/conf/bcs-services/bcs-user-manager/bcs-user-manager.json.template
  resources/resources.md
Labels: confirmed, feature, inner

#736 Feature: bcs-storage publish specific resource to message queue
  bcs-services/bcs-storage/app/options/options.go
  bcs-services/bcs-storage/storage/actions/lib/metrics.go
  bcs-services/bcs-storage/storage/actions/lib/store.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic/utils.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamicquery/utils.go
  bcs-services/bcs-storage/storage/actions/v1http/events/events-action.go
  bcs-services/bcs-storage/storage/actions/v1http/events/utils.go
  bcs-services/bcs-storage/storage/apiserver/health.go
  bcs-services/bcs-storage/storage/apiserver/queueOptions.go
  bcs-services/bcs-storage/storage/apiserver/resource.go
  bcs-services/bcs-storage/storage/watchbus/dispatcher.go
  install/conf/bcs-services/bcs-storage/bcs-storage.json.template
  install/conf/bcs-services/bcs-storage/queue.conf.template
  scripts/base.env
Labels: confirmed, feature, inner, service

#740 Feature: switch bcs-storage service registry to etcd; issue #739
  bcs-services/bcs-storage/storage/storage.go
Labels: confirmed, feature, inner

#741 pipeline modification
  bcs-k8s/bcs-gamedeployment-operator/cmd/gamedeployment-operator/main.go
  bcs-k8s/bcs-gamestatefulset-operator/cmd/gamestatefulset-operator/main.go
  bcs-services/bcs-gateway-discovery/app/zookeeper.go
  install/conf/bcs-k8s-master/bcs-k8s-watch/container-start.sh
  install/conf/bcs-services/bcs-gateway-discovery/Dockerfile.gateway
  install/conf/bcs-services/bcs-gateway-discovery/apisix-start.sh
  install/conf/bcs-services/bcs-gateway-discovery/container-start.sh
  install/conf/bcs-services/bcs-storage/container-start.sh
  install/conf/bcs-services/bcs-user-manager/bcs-user-manager.json.template
  install/conf/bcs-services/bcs-user-manager/container-start.sh
Labels: confirmed, feature, inner

#743 Fix: bcs-storage queue init & queueFlag problem; issue #742
  bcs-services/bcs-storage/storage/actions/v1http/dynamic/utils.go
  bcs-services/bcs-storage/storage/actions/v1http/events/utils.go
  bcs-services/bcs-storage/storage/apiserver/resource.go
  bcs-services/bcs-storage/storage/errors/errors.go
Labels: confirmed, feature, inner

#744 fix: gamestatefulset rollingUpdate.Partition panic && gamestatefulset monotonic control for updated version replica, not all replica
  bcs-k8s/bcs-gamestatefulset-operator/pkg/controllers/game_stateful_set_control.go
  bcs-k8s/bcs-gamestatefulset-operator/pkg/util/canary/canary.go
Labels: confirmed, feature, inner, scheduler

#748 容器化调试问题修复
  bcs-common/go.mod
  bcs-common/pkg/bcsapi/client.go
  bcs-common/pkg/registry/etcd.go
  bcs-common/pkg/scheduler/schetypes/application.go
  bcs-common/pkg/scheduler/schetypes/message.go
  bcs-common/pkg/scheduler/types/application.go
  bcs-common/pkg/scheduler/types/message.go
  bcs-k8s/bcs-gamestatefulset-operator/pkg/controllers/game_stateful_set_control.go
  bcs-k8s/bcs-k8s-watch/app/bcs/cluster.go
  bcs-services/bcs-api/options/options.go
  bcs-services/bcs-client/go.mod
  bcs-services/bcs-gateway-discovery/app/adapter.go
  bcs-services/bcs-gateway-discovery/app/micro.go
  bcs-services/bcs-gateway-discovery/app/server.go
  bcs-services/bcs-gateway-discovery/app/zookeeper.go
  bcs-services/bcs-gateway-discovery/discovery/interface.go
  bcs-services/bcs-gateway-discovery/discovery/micro.go
  bcs-services/bcs-gateway-discovery/register/apisix/apisix.go
  docs/features/bcs-api-gateway/api-gateway方案.md
  go.sum
  install/conf/bcs-services/bcs-storage/Dockerfile
  install/conf/bcs-services/bcs-storage/container-start.sh
Labels: bug, inner, service

#749 fix: dependency fix, issue #0
  bcs-k8s/bcs-gamedeployment-operator/go.mod
  bcs-k8s/bcs-gamestatefulset-operator/go.mod
  bcs-k8s/bcs-k8s-custom-scheduler/go.mod
  bcs-services/bcs-storage/storage/actions/v1http/dynamic/utils.go
  bcs-services/bcs-webhook-server/go.mod
  go.sum
Labels: confirmed, inner
