Repository TencentBlueKing/bk-bcs, pull requests merged in 2021-07, with the labels that each got.

#941 change bcs-webhook-server randhostport plugin docs
  docs/features/bcs-webhook-server/plugins/randhostport/design.md
Labels: confirmed, document, inner

#943 storage 更新index key类型为bson.D
  bcs-services/bcs-storage/storage/actions/lib/store.go
  bcs-services/bcs-storage/storage/actions/v1http/dynamic/utils.go
  bcs-services/bcs-storage/storage/store/mongo/mongo.go
  go.mod
Labels: confirmed, inner, service

#945 fix: root mod remove services package; #944
  go.mod
Labels: confirmed, document, inner

#947 fix: fix deadlock when haproxy client timeout; issue #946
  go.mod
Labels: bug, confirmed, inner, mesos, network
